# -*- coding: utf-8 -*-
"""Jimin_5.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bU82gwjlUWfslLb7P5BNPK6R9wNIB0gA
"""

"""Team weighting rule v5 (2026-10-06): v4 (momentum tilt + earnings-miss -> cash + shock S0 -> S1) with the 12-1 month
momentum score replaced by RESIDUAL momentum (Blitz, Huij & Martens 2011).

Residual momentum of stock i at decision day t:
  daily log return r_i,d = beta_m * mkt_d + beta_s * sec_d + e_i,d
    mkt_d = equal-weight average return of the 30 stocks, sec_d = average return of the other stocks in the same sector group
    (beta_m, beta_s) re-estimated every day d by OLS on the 120 trading days before d
  score_i = sum of e_i,d over d = t-252 .. t-22  /  std of the same residuals   (12-1 month window, skip last month)
Everything else is v4: theta 0.25%p tilt around S/30, cap 30%, k=0.5, g=5%, Round 1 only, EPS miss < -0.5% -> 0 for 15
trading days, previous-day EW drop <= -2% -> S1 once (same relative weights; held stocks are never sold on a shock).
Shock cut-off (2026-10-06): the raise is only allowed up to window day SHOCK_LAST_DAY = 10 (day 0 = first decision day);
a shock seen later is just held through, because the 15-day window has too little time left for the rebound
(backtest_rba/trend_resmom/shock_timing.py, shock_cutoff.py: 50-team position -0.11 +- 0.04 vs no cut-off).

Needs >= 373 daily closes before the decision day (252 + 120 + 1). The testbed only has history from 2021-01-04, so a live /
local runner must supply the longer history (Yahoo Finance daily closes). With shorter history the score falls back to v4's
12-1 momentum.
Backtests (2026-10-06, backtest_rba/trend_resmom/, backtest_rba/testbed_local/): see those folders.
Self-contained (no import of jimin_test_v4; its helpers are copied below). Uploaded to the team testbed on 2026-10-06.
"""
import numpy as np
import pandas as pd
from testbed import get_daily_close, zero_weights


# ---------------- helpers copied from jimin_test_v4 (miss table, 12-1 score, shock test) ----------------
MISS_DAYS = 15          # trading days to stay out after a miss
MISS_THR = -0.5         # EPS surprise (%) below which it counts as a miss

MISS_TABLE = {
    "AAPL": "20230203:-3.8",
    "AMZN": "20190726:-6.5 20191025:-7.1 20200501:-18.0 20211029:-30.9 20220429:-191.6 20220729:-273.3 20230203:-81.7",
    "BA": "20190424:-1.0 20191023:-31.4 20200129:-97.6 20200429:-14.3 20200729:-89.6 20210127:-826.0 20210429:-41.0 20211027:-299.0 20220126:-4731.9 20220427:-995.8 20220727:-246.3 20221026:-7213.3 20230125:-961.3 20230426:-20.9 20231025:-25.0 20240731:-44.2 20241023:-19.7 20250128:-56.1 20251029:-214.4 20260728:-141.5",
    "BAC": "20200415:-33.4 20220718:-2.1 20240112:-45.6 20240416:-1.8",
    "CAT": "20190128:-14.7 20190724:-9.4 20191023:-8.1 20200428:-4.5 20230131:-4.2 20241030:-3.4 20250430:-2.2 20250805:-3.7",
    "CRM": "20241204:-1.5",
    "CVX": "20190802:-2.8 20200731:-73.2 20210129:-111.4 20210430:-4.6 20220128:-18.0 20220429:-2.7 20230127:-4.8 20231027:-17.1 20240802:-14.9 20250131:-2.3",
    "DIS": "20190807:-22.4 20200506:-33.0 20211111:-23.4 20220512:-9.2 20221109:-46.9 20230511:-0.9",
    "GE": "20190131:-24.1 20200429:-38.0 20200729:-66.4 20210126:-6.3 20221025:-28.1",
    "GOOGL": "20190430:-5.0 20191029:-18.8 20200429:-3.4 20220427:-4.4 20220727:-5.0 20221026:-15.3 20230203:-11.9",
    "GS": "20191015:-1.8 20200115:-14.0 20200415:-7.4 20220118:-9.4 20230117:-42.4 20230719:-19.6 20231017:-1.0",
    "INTC": "20220729:-58.3 20230127:-50.5 20240802:-80.2 20241101:-1533.5 20250725:-1169.5",
    "JPM": "20190115:-9.5 20200714:-10.4 20220413:-2.9 20220714:-4.8 20240112:-15.7 20260113:-3.9",
    "LLY": "20201027:-10.0 20210427:-10.9 20210803:-1.0 20211026:-1.2 20220203:-0.7 20220804:-26.3 20230427:-6.3 20241030:-19.5 20250501:-3.4",
    "META": "20190425:-47.3 20190725:-50.8 20220203:-4.1 20220728:-3.4 20221027:-12.1 20230202:-21.5 20251030:-84.3 20260730:-14.4",
    "MSFT": "20220727:-2.7",
    "NEE": "20190125:-3.0 20200124:-2.5",
    "NKE": "20190628:-5.4 20200325:-2.7 20200626:-858.5 20230630:-2.3",
    "NVDA": "20220825:-1.5 20221117:-17.3",
    "PFE": "20200128:-4.5 20210202:-9.7",
    "PYPL": "20200507:-11.6 20220202:-1.0 20240430:-11.4 20260203:-4.4",
    "T": "20200422:-1.4 20240124:-3.2 20240724:-0.6 20250423:-0.9",
    "TMO": "20230726:-5.2",
    "TSLA": "20190131:-6.5 20190425:-209.6 20190725:-182.3 20210128:-23.9 20231019:-9.8 20240125:-3.5 20240424:-8.1 20240724:-16.1 20250130:-5.1 20250423:-34.9 20250724:-1.1 20251023:-10.5 20260723:-39.1",
    "UNH": "20250417:-1.3 20250729:-8.2",
    "WMT": "20200218:-3.8 20210218:-8.0 20220517:-12.1 20250821:-8.0",
    "XOM": "20190426:-24.5 20190802:-13.6 20200131:-9.6 20200731:-17.1 20220429:-7.0 20230728:-3.9 20231027:-3.8 20240426:-4.8",
}


def _parse_table():
    out = {}
    for t, s in MISS_TABLE.items():
        out[t] = sorted((pd.Timestamp(x.split(":")[0]), float(x.split(":")[1])) for x in s.split() if x)
    return out


_MISS = _parse_table()


def add_miss(ticker, yyyymmdd, surprise):
    """Register a new miss at runtime (effective day = first Round-1 day on which the report is public)."""
    _MISS.setdefault(ticker, []).append((pd.Timestamp(yyyymmdd), float(surprise)))
    _MISS[ticker].sort()


def _zscore(x):
    x = np.asarray(x, dtype=float)
    m, s = np.nanmean(x), np.nanstd(x)
    z = (x - m) / s if s > 0 else np.zeros_like(x)
    return np.clip(np.nan_to_num(z), -2.5, 2.5)


def _decision_day(observation, daily):
    """Calendar date of the current Round-1 decision. Prefer an explicit date in the observation; otherwise the next
    business day after the last completed daily close."""
    rnd = observation.get("round", {}) or {}
    for key in ("day", "date", "trading_day", "as_of", "deadline", "execution_time", "id"):
        v = rnd.get(key) if isinstance(rnd, dict) else None
        if v:
            try:
                s = str(v)
                if key == "id":
                    s = s.split("-r")[0].split("-", 1)[1]        # validation-YYYY-MM-DD-r1
                return pd.Timestamp(s[:10])
            except Exception:
                pass
    for key in ("as_of", "timestamp", "date", "day"):
        v = observation.get(key)
        if v:
            try:
                return pd.Timestamp(str(v)[:10])
            except Exception:
                pass
    last = pd.Timestamp(daily.index[-1]).normalize()
    return last + pd.offsets.BDay(1)


def _excluded(observation, daily, syms):
    """Boolean mask: stocks with a miss whose effective day is within the last MISS_DAYS trading days (inclusive of today)."""
    today = _decision_day(observation, daily)
    idx = pd.DatetimeIndex(daily.index).normalize()
    past = idx[idx < today]
    start = past[-(MISS_DAYS - 1)] if len(past) >= MISS_DAYS - 1 else (past[0] if len(past) else today)
    out = np.zeros(len(syms), dtype=bool)
    for j, t in enumerate(syms):
        for d, s in _MISS.get(t, []):
            if s < MISS_THR and start <= d <= today:
                out[j] = True
                break
    return out


SHOCK_DROP = -0.02        # previous-day equal-weight return (close-to-close) that counts as a shock


def _signal_121(daily, n):
    if len(daily) < 253:
        return np.zeros(n)
    raw = daily.iloc[-22].values / daily.iloc[-253].values - 1   # return from t-252 to t-21
    return _zscore(raw)


def _shock_yesterday(daily):
    """True if the equal-weight average of the stocks fell by SHOCK_DROP or more from the close two days ago to the
    last close (the last completed trading day before this Round 1)."""
    if len(daily) < 2:
        return False
    r = daily.iloc[-1].values / daily.iloc[-2].values - 1
    r = r[np.isfinite(r)]
    return bool(len(r)) and float(np.mean(r)) <= SHOCK_DROP



# ---------------- v5 ----------------
NAME = "jimin_test_v5"
LOOKBACK = 400
BETA_WIN = 120
SHOCK_LAST_DAY = 10                                  # raise S only if today's window day index <= 10
PHASE_START = {"validation": ("2026-10-08", "2026-10-09"), "official": ("2026-10-12", "2026-10-30")}
_START = {}                                          # fallback cache: window start = first decision day with an empty book
SECTOR = {'GOOGL': 'Comm', 'META': 'Comm', 'NEE': 'Comm', 'T': 'Comm', 'DIS': 'Comm',
          'WMT': 'Cons', 'KO': 'Cons', 'TSLA': 'Cons', 'AMZN': 'Cons', 'NKE': 'Cons',
          'BAC': 'Fin', 'GS': 'Fin', 'PYPL': 'Fin', 'JPM': 'Fin', 'V': 'Fin',
          'UNH': 'Hlth', 'JNJ': 'Hlth', 'LLY': 'Hlth', 'PFE': 'Hlth', 'TMO': 'Hlth',
          'XOM': 'Ind', 'GE': 'Ind', 'CVX': 'Ind', 'CAT': 'Ind', 'BA': 'Ind',
          'MSFT': 'Tech', 'INTC': 'Tech', 'CRM': 'Tech', 'NVDA': 'Tech', 'AAPL': 'Tech'}


def residual_momentum(daily, L=BETA_WIN):
    """daily: DataFrame of closes (rows = days, oldest first). Returns raw residual-momentum score per column (NaN if short)."""
    X = daily.values.astype(float)
    n = X.shape[1]
    if len(X) < 252 + L + 1:
        return None
    R = np.log(X[1:] / X[:-1])                       # R[j] = return into day j+1
    R = np.where(np.isfinite(R), R, np.nan)
    ok = np.isfinite(R)
    Rz = np.where(ok, R, 0.0)
    mkt = Rz.sum(1) / np.maximum(ok.sum(1), 1)
    sec = np.array([SECTOR.get(c, c) for c in daily.columns])
    M = (sec[:, None] == sec[None, :]).astype(float)
    cnt = ok.astype(float) @ M
    sec_ex = np.where(cnt - ok > 0, (Rz @ M - Rz) / np.maximum(cnt - ok, 1), mkt[:, None])
    T = len(R)
    x1 = np.repeat(mkt[:, None], n, 1); x2 = sec_ex

    def ws(Z):                                        # sum over [t-L, t) for each t
        cs = np.cumsum(np.vstack([np.zeros((1, n)), Z]), 0)
        out = np.full((T, n), np.nan)
        out[L:] = cs[L:T] - cs[:T - L]
        return out
    S11, S12, S22, S1y, S2y = ws(x1 * x1), ws(x1 * x2), ws(x2 * x2), ws(x1 * Rz), ws(x2 * Rz)
    det = S11 * S22 - S12 ** 2
    with np.errstate(all="ignore"):
        b1 = (S22 * S1y - S12 * S2y) / det
        b2 = (S11 * S2y - S12 * S1y) / det
    E = R - b1 * x1 - b2 * x2
    # last row of R = return into the last completed day (t-1). formation days t-252 .. t-22  -> R rows [-252, -21)
    e = E[-252:-21]
    with np.errstate(all="ignore"):
        s = np.nansum(e, 0) / (np.nanstd(e, 0) + 1e-12)
    s[np.isnan(e).any(0)] = np.nan
    return s


def _signal(daily, n):
    s = residual_momentum(daily)
    if s is None:
        return _signal_121(daily, n)                  # not enough history -> v4's 12-1 momentum
    return _zscore(s)


def _window_day(observation, daily, started):
    """Trading-day index of today inside the evaluation window (0 = first decision day)."""
    today = _decision_day(observation, daily)
    start = None
    win = observation.get("window")
    w = observation.get("window_start") or (win.get("start") if isinstance(win, dict) else None)
    if w:
        start = pd.Timestamp(str(w)[:10])
    if start is None:
        rid = str((observation.get("round") or {}).get("id", ""))
        for ph, (a, b) in PHASE_START.items():
            if rid.startswith(ph) and pd.Timestamp(a) <= today <= pd.Timestamp(b):
                start = pd.Timestamp(a)
    if start is None:
        if not started:
            _START["d"] = today
        start = _START.get("d", today)
    idx = pd.DatetimeIndex(daily.index).normalize()
    return int(((idx >= start) & (idx < today)).sum())


def _rule(observation, S0, S1=None, theta=0.0025, k=0.5, g=0.05, miss_rule=True, last_day=SHOCK_LAST_DAY):
    # identical to jimin_test_v4._rule except the history length, the score and the shock cut-off
    syms = observation["symbols"]
    n = len(syms)
    port = observation["portfolio"]
    started = bool(port.get("positions"))
    if started and observation["round"]["number"] != 1:
        return None
    daily = get_daily_close(observation, lookback=LOOKBACK).reindex(columns=syms)
    w = port.get("weights") or {}
    cur = np.array([float(w.get(s, 0.0)) for s in syms])
    switched = S1 is not None and started and cur.sum() > (S0 + S1) / 2
    fire = (S1 is not None and started and not switched and _shock_yesterday(daily)
            and (last_day is None or _window_day(observation, daily, started) <= last_day))
    if not started:
        _window_day(observation, daily, started)              # register the window start for the fallback cache
    S = S1 if (switched or fire) else S0
    z = _signal(daily, n)
    target = np.clip(S / n + theta * z, 0.0, 0.30)
    if target.sum() > 0:
        target = target * (S / target.sum())
    excl = _excluded(observation, daily, syms) if miss_rule else np.zeros(n, dtype=bool)
    target[excl] = 0.0
    if not started or fire:
        new = target
    else:
        must_sell = bool((excl & (cur > 1e-4)).any())
        if np.abs(target - cur).sum() < g and not must_sell:
            return None
        new = cur + k * (target - cur)
        new[excl] = 0.0
    new = np.clip(new, 0.0, 0.30)
    if new.sum() > 1:
        new = new / new.sum()
    out = zero_weights()
    out.update({s: float(v) for s, v in zip(syms, new)})
    return out


def sh25_40(observation): return _rule(observation, S0=0.25, S1=0.40)
def sh15_40(observation): return _rule(observation, S0=0.15, S1=0.40)
def sh25_60(observation): return _rule(observation, S0=0.25, S1=0.60)
def sh25_40_nocut(observation): return _rule(observation, S0=0.25, S1=0.40, last_day=None)
def v3_s25(observation): return _rule(observation, S0=0.25)
def strategy(observation): return sh25_40(observation)
sh25_40.name = "v5 resmom S25->40 shock (raise until day 10)"; sh25_40_nocut.name = "v5 resmom S25->40 shock (no cut-off)"; sh15_40.name = "v5 resmom S15->40 shock"; sh25_60.name = "v5 resmom S25->60 shock"
v3_s25.name = "v5 resmom S25 (no shock)"; strategy.name = "jimin_test_v5 (resmom, S25->40 shock until day 10)"


if __name__ == "__main__":
    import sys
    if "--refresh" in sys.argv:                           # print fresh MISS_TABLE rows from yfinance (needs internet)
        import yfinance as yf
        for t in sorted(MISS_TABLE):
            e = yf.Ticker(t).get_earnings_dates(limit=12).reset_index()
            e.columns = ["dt", "eps_est", "eps_rep", "surprise"]
            e["dt"] = pd.to_datetime(e.dt, utc=True).dt.tz_convert("America/New_York").dt.tz_localize(None)
            e = e.dropna(subset=["surprise"])
            e = e[e.surprise < MISS_THR]
            eff = np.where(e.dt.dt.hour < 9, e.dt.dt.normalize(), e.dt.dt.normalize() + pd.Timedelta(days=1))
            print(f'    "{t}": "' + " ".join(f"{pd.Timestamp(d).strftime('%Y%m%d')}:{s:.1f}" for d, s in zip(eff, e.surprise)) + '",')